# Generated by Django 5.1 on 2024-08-09 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0003_proveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_puertas', models.IntegerField()),
                ('cilindrada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_de_combustible', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.categoria')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.color')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.marca')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.modelo')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.pais')),
            ],
        ),
    ]
