# Generated by Django 5.1 on 2024-08-09 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0005_comentario_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='ciudad_id',
        ),
        migrations.RemoveField(
            model_name='sede',
            name='provincia_id',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Provincia',
        ),
        migrations.DeleteModel(
            name='Sede',
        ),
    ]
