# Generated by Django 5.1 on 2024-08-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0009_ciudad_sede'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelo',
            name='marca',
        ),
    ]
