# Generated by Django 5.1 on 2024-08-09 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0010_remove_modelo_marca'),
    ]

    operations = [
        migrations.AddField(
            model_name='sede',
            name='nombre',
            field=models.CharField(default='nombre', max_length=200),
            preserve_default=False,
        ),
    ]
