# Generated by Django 5.1 on 2024-08-10 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0011_sede_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sede',
            name='provincia_id',
        ),
    ]
