# Generated by Django 5.0.4 on 2024-11-28 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concesionaria', '0012_remove_sede_provincia_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='cilindrada',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='cilindrada'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.color', verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.marca', verbose_name='marca'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.modelo', verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='numero_de_puertas',
            field=models.IntegerField(verbose_name='número de puertas'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.pais', verbose_name='pais'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='tipo_de_combustible',
            field=models.CharField(max_length=50, verbose_name='tipo de combustible'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.provincia', verbose_name='provincia'),
        ),
        migrations.AlterField(
            model_name='color',
            name='nombre',
            field=models.CharField(max_length=50, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='autor'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='concesionaria.auto', verbose_name='auto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='rating',
            field=models.IntegerField(verbose_name='puntuación'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='text',
            field=models.TextField(verbose_name='texto'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='modelo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='teléfono'),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='ciudad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concesionaria.ciudad', verbose_name='ciudad'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='direccion',
            field=models.CharField(max_length=255, verbose_name='dirección'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='gerente',
            field=models.CharField(max_length=100, verbose_name='gerente'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='sede',
            name='telefono',
            field=models.CharField(max_length=20, verbose_name='teléfono'),
        ),
    ]
